PickAndBook/Controllers/CompanyAnonymousController.cs
using System;
using System.Web.Mvc;
using PickAndBook.Data;
using PickAndBook.Data.Models;
using System.Linq;

namespace PickAndBook.Controllers
{
    [AllowAnonymous]
    public class CompanyAnonymousController : BaseController
    {
        public CompanyAnonymousController(IPickAndBookData data) 
            : base(data)
        {
        }

        // GET: CompanyAnonymous
        public ActionResult Index()
        {
            var companies = this.Data.Companies.All().ToList();
            return View(companies);
        }

        public ActionResult ByCategory(Guid? categoryId)
        {
            var companies = this.Data.Companies.GetCompaniesByCategoryId(categoryId);
            if (companies == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("Index", companies.ToList());
        }

        public ActionResult Detail(Guid? companyId)
        {
            Company currentCompany = this.Data.Companies.GetById(companyId);
            if (currentCompany == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(currentCompany);
        }
    }
}

PickAndBook/Controllers/HomeController.cs
using PickAndBook.Common;
using PickAndBook.Data;
using PickAndBook.Data.Common;
using PickAndBook.Data.Repositories.Contracts;
using PickAndBook.Services.Contracts;
using System.Linq;
using System.Web.Caching;
using System.Web.Mvc;

namespace PickAndBook.Controllers
{
    [AllowAnonymous]
    public class HomeController : BaseController
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly ICompanyRepository companyRepository;
        // Use SingleR
        private readonly ICompanyService companyService;

        public HomeController(IPickAndBookData data)
            : base(data)
        {
            this.categoryRepository = data.Categories;
            this.companyRepository = data.Companies;
        }

        // Use SingleR
        public HomeController(IPickAndBookData data, ICompanyService companyService)
            : base(data)
        {
            this.categoryRepository = data.Categories;
            this.companyRepository = data.Companies;
            this.companyService = companyService;
        }



        public ActionResult Index()
        {
            // throw new HttpException(404, "Test error behavior");
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [OutputCache(Duration = 3600, VaryByParam = "none", VaryByCustom = "CustomSqlDependency")]
        public ActionResult HomeCategories()
        {
            var categories = this.categoryRepository.All().ToList();
            // this.ViewBag.Current = DateTime.Now;
            return PartialView("_HomeCategories", categories);
        }

        public ActionResult LastAddedCompanies()
        {
            //// Use SingleR
            //var companies = this.companyService.GetLastAddedCompanies()
            //       .Take(DataConstants.LastRegisteredCompaniesCount)
            //       .ToList();
            var companies = this.companyService.GetLastAddedCompanies().ToList();
            // this.ViewBag.Current = DateTime.Now;
            // var companies = this.companyRepository.GetLastAddedCompanies().ToList();
            return PartialView("_LastAddedCompanies", companies);
        }

        public ViewResult Error()
        {
            return this.View("Error");
        }
    }
}

PickAndBook/Controllers/RegisterCompanyController.cs
using System.Web;
using System.Web.Mvc;
using System.Linq;
using PickAndBook.Data;
using PickAndBook.Data.Models;
using PickAndBook.Data.Common;
using PickAndBook.Helpers.Contracts;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;

namespace PickAndBook.Controllers
{
    [Authorize(Roles = DataConstants.ClientRoleName)]
    public class RegisterCompanyController : BaseController
    {
        private IFileUploader fileUploader;
        private IUserRoleManager userRoleManager;

        public RegisterCompanyController(IPickAndBookData data) 
            : base(data)
        {
        }

        public RegisterCompanyController(IPickAndBookData data, IFileUploader fileUploader, IUserRoleManager userRoleManager)
            : base(data)
        {
            this.fileUploader = fileUploader;
            this.userRoleManager = userRoleManager;
        }

        public ActionResult Index()
        {
            Company currentCompany = this.Data.Companies.GetCompanyByUserId(User.Identity.GetUserId());
            if (currentCompany != null)
            {
                return View("CompanyDetails", currentCompany);
            }

            currentCompany = new Company();
            ViewBag.CategoryId = new SelectList(this.Data.Categories.All().ToList(), "CategoryId", "CategoryName");
            return View(currentCompany);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(Company company, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    string uploadedImage = this.fileUploader.UploadFile(upload, Common.Constants.CompaniesImageFolder);
                    if (uploadedImage == "")
                    {
                        ModelState.AddModelError(Common.Constants.FileCannotBeUploadedKey, Common.Constants.FileCannotBeUploaded);
                        return View(company);
                    }
                    company.CompanyImage = uploadedImage;
                }

                this.Data.Companies.Add(company);
                this.Data.SaveChanges();

                var llRoleChanged = await this.userRoleManager.ChangeUserRoleFromClientToCompany(HttpContext, User);
                if (llRoleChanged)
                {
                    return View("CompanyDetails", company);
                }
                ModelState.AddModelError("Roles", "User roles not assigned!");
            }

            ViewBag.CategoryId = new SelectList(this.Data.Categories.All().ToList(), "CategoryId", "CategoryName", company.CategoryId);
            return View(company);
        }
    }
}

PickAndBook/Views/Home/About.cshtml
@{
    ViewBag.Title = "About \"Pick and Book\"";
}
<h2>@ViewBag.Title.</h2>

<p>The idea of Pick and Book application is to provide an easy way to pick & book services in different kind of Companies.</p>
<p>The Companies are grouped in Categories. There will be added a possibility to set Working Times for Companies and to schedule booked hours.</p>
<p>The System provides search functionality by Company Name and Description. </p>
<hr />
<a href="https://telerikacademy.com/Users/Mirka" target="_blank">Mirka</a>

PickAndBook/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Information";
}
<h2>@ViewBag.Title</h2>
<h3>Hour For Ltd.</h3>

<address>
    Varna, 9010<br />
    <abbr title="Phone">P:</abbr>
    0896607931
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:support@hour.for">Support@pick.book</a><br />
</address>

PickAndBook/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.Action("HomeCategories", "Home")
@*@Html.Action("LastAddedCompanies", "Home")*@
@*// Use SingleR*@
<div id="lastAddedCompanies">
</div>

<div class="row">
    <div class="col-md-6">
        <div class="jumbotron" id="joinus">
            <h1>Join Us</h1>
            <p class="lead">If you own a company that offers hourly services and you want to be found by more people join us!</p>
            <p>@Html.ActionLink("Register Company", "Index", "RegisterCompany")</p>
        </div>
    </div>
    <div class="col-md-6">
        <div class="jumbotron" id="pickandbook">
            <h1>Pick and Book</h1>
            <p class="lead">
                You can book an hour for any service provided by our partners with one click only.
                Find your service, pick your hour and book!
            </p>
            <p>@Html.ActionLink("Pick and Book", "Index", "CompanyAnonymous")</p>
        </div>
    </div>
</div>

<div class="jumbotron" id="contactus">
    <h1>Here for you</h1>
    <p class="lead">Please do not hesitate to contact our Live Help or send an e-mail to support@hour.for if you need any help at all.</p>
    <p>@Html.ActionLink("Contact us", "Contact", "Home")</p>
</div>

@*// Use SingleR*@
@section Scripts {
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("/signalr/hubs") 
    @Scripts.Render("~/scripts/get.last.added.companies.js")
}

PickAndBook/Views/Home/_HomeCategories.cshtml
@model IList<PickAndBook.Data.Models.Category>

<div class="jumbotron row">
    @*<p class="lead">Time: @ViewBag.Current</p>*@
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="categoryImage col-md-4" style="background:url(@Model[i].CategoryImage) center 100%">
            <h2>@Model[i].CategoryName</h2>
            <p class="lead">@Model[i].CategoryDescription</p>
            @Html.ActionLink("View companies", "ByCategory", "CompanyAnonymous", new { categoryId = @Model[i].CategoryId }, new { Area = "" })
       </div>
    }
</div>

PickAndBook/Views/Home/_LastAddedCompanies.cshtml
@model IList<PickAndBook.Data.Models.Company>

<div class="jumbotron row">
    @*<p class="lead">Time: @ViewBag.Current</p>*@
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="CompanyImage col-md-4" style="background:url(@Model[i].CompanyImage) center 100%">
            <h2>@Model[i].CompanyName</h2>
            <p class="lead">@Model[i].CompanyDescription</p>
            @Html.ActionLink("View company", "Detail", "CompanyAnonymous", new { companyId = @Model[i].CompanyId }, new { Area = "" })
        </div>
    }
</div>